### PR TITLE
Added Jotto

### LINKED ISSUE #879: Meeting function potentially hits an error accessing undefined value
Meeting.js has a `get` property for `hasPlurality()`.
If `sortedCount` is an empty array, `sortedCount[0][1]` will throw an error.

### LINKED ISSUE #880: Player function falsely assumes player did not vote in a meeting
In the `hasVotedInAllMeetings()` function of `Player.js` (core), the check for "player has not voted" only references `canVote`, `canUpdateVote`, and whether the vote is undefined, but not if the meeting is a voting meeting. This breaks if the player has a non-voting meeting (such as a speech-only meeting).

### LINKED ISSUE #881: VegKickMeeting does not check if player exists in members
If a player in the game is not a member of the meeting, then they cannot "unvote" in the meeting.

`VegKickMeeting.resetKicks()` attempts to access `this.members[player.id]` without checking if player exists as a member.

### LINKED ISSUE #882: React does not recognize 'enterKeyHint'
React does not recognize `enterKeyHint` on the DOM, suggests `enterkeyhint`.

### PR DESCRIPTION
**Pull request by ghost**
This Jotto push should be a fully functional game for 2-4 players.
There are definitely many minor improvements that can be made, but for the time being it works :)

Long list of changes below:

**Additional directly unrelated changes/bugfixes that were made to make Jotto work:
Will be tracked in new GitHub issues for the sake of documenting.**
- ~~`Games/core/History.js` Line 13-14: Jotto uses extraInfo to carry word/guess history~~ 
  - (already introduced in #876)
- `Games/core/Meeting.js` Line 889-891: If there's no sorted count of votes, then you can't check sortedCount[0][1]
  - (Resolves #879)
- `Games/core/Player.js` Line 275: Jotter speech meeting is not voting, but considers members as "not voted" 
  - (Resolves #880)
- `Games/core/VegKickMeeting.js` Line 38-40: If the player is not a member, then you can't make them unvote 
  - (Resolves #881)
- `react_main/src/pages/Game/Game.jsx` Line 1644: React wants it as enterkeyhint instead of enterKeyHint 
  - (Resolves #882)
- `react_main/src/pages/Game/Game.jsx` Line 2017: Exporting ActionButton. Takes into consideration that games may have custom actions and will need ActionButton to account for VegKickMeeting

**New non-Jotto-specific features that were created**
- `react_main/src/pages/Game/Game.jsx` Line 847-996: SidePanelLayout and CombinedTextMeetingLayout can be used for more than just Jotto. CombinedTextMeetingLayout condenses all messages from every state rather than just the current state. SidePanelLayout eliminates the right-panel in favor of a larger left-panel and center-panel (main-panel here).
- `react_main/src/css/game.css` Line 191-199: Panel CSS for SidePanelLayout
- ~~`react_main/src/css/game.css` Line 173: justify-content: center is better for non-fullscreen~~
  - (already introduced in #877)

**Changes to the core to include Jotto**
- `data/constants.js` Line 3 & 10 & 17 & 73-84 & 111: Includes Jotto, as well as alignment/state/modifier configuration (standard for all game types)
- `data/constants.js` Line 170-171: Jotto role count range to force 2-4 players
- `data/roles.js` Line 1295-1303: Adds Jotter role to new Jotto type (game type entry standard for all game types)
- `react_main/public/images/roles.png`: Jotter role icon
- `react_main/src/css/roles.css` Line 936-945: Jotter role icon position
- `react_main/src/pages/Game/Game.jsx` Line 14 & 675: Display JottoGame UI (standard for all game types)
- `react_main/src/pages/Play/Play.jsx` Line 22-25 & 101-102 & 124-125 & 147-148: Jotto host/setup/learn (standard for all game types)
- `react_main/src/Constants.jsx` Line 1 & 9 & 17: Include Jotto game type, states, and alignments (standard for all game types)
- `react_main/src/Constants.jsx` Line 59-788: List of legal Jotto word inputs. Stored as an Object to act as a hashmap to reduce search time.
- `routes/game.js` Line 632-634: Include Jotto host setting checks (standard for all game types)
- `routes/setup.js` Line 473-478: Jotto player count check
- `routes/setup.js` Line 804-808 & 869-871: Include Jotto setup creation setting checks (standard for all game types)

**Jotto files:**
- `Games/types/Jotto/const/Priority.js`: Just a formality to have a priority constant even if there's only one
- `Games/types/Jotto/roles/cards`: Contains Jotter (Jotto player) core card for meetings and the win condition card
- `Games/types/Jotto/roles/Jotter`: Contains Jotter role, which stores the alignment and cards, plus game details such as words and opponent.
- `Games/types/Jotto/Action.js`: Extends Action with no overrides. Used by Game.js
- `Games/types/Jotto/Card.js`: Extends Card with no overrides. Used by JotterCore.js and WinCorrectGuess.js
- `Games/types/Jotto/Game.js`: The entire Jotto core game logic
- `Games/types/Jotto/Player.js`: Extends Player, adds a socket listener for jotto word submission (Jotto meeting vote)
- `Games/types/Jotto/Role.js`: Extends Role with no overrides. Used by Jotter.js
- `Games/types/Jotto/Winner.js`: Extends Winners, overrides queueAlerts to display individual winners instead of the group.
- (In `react_main/src/pages/Play`) `CreateJottoSetup.jsx` & `HostJotto.jsx` & `LearnJotto.jsx`: Setup/host/learn pages for Jotto, using the Mafia game type as a reference (standard for all game types)
- `react_main/src/pages/Game/JottoGame.jsx`: The entire JottoGame UI.
- `react_main/src/css/jotto.css`: JottoGame UI stylesheet.

### CODE REVIEW

**Comment by minokr** [comment]
Jotter icon is just Villager with different colors and a pencil in the hand

**Review by R9H9 — COMMENTED** [review]
I'll look into this tonight, when I get time.

**Review by R9H9 — APPROVED** [review]
Looks about right to me!
